source :rubygems

gem "coffee-script"
gem "excon"
gem "excon-slides_instrumentor"
gem "rack"
gem "rack-instruments"
gem "rack-robots"
gem "rack-ssl"
gem "redcarpet"
gem "sass"
gem "sinatra"
gem "slides"
gem "slim"
gem "sprockets"
gem "thin"
