require_relative "facts/config"
require_relative "facts/filters/link_filter"
require_relative "facts/filters/markdown_filter"
require_relative "facts/filters/tex_filter"
require_relative "facts/models/category"
require_relative "facts/models/fact"
